export const LANGUAGES = [
  { code: "en-US", label: "English (US)" },
  { code: "en-GB", label: "English (UK)" },
  { code: "tr-TR", label: "Türkçe" },
  { code: "es-ES", label: "Español (España)" },
  { code: "es-MX", label: "Español (México)" },
  { code: "de-DE", label: "Deutsch" },
  { code: "fr-FR", label: "Français" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "it-IT", label: "Italiano" },
  { code: "ru-RU", label: "Русский" },
  { code: "ar-SA", label: "العربية" },
  { code: "zh-CN", label: "中文 (简体)" },
  { code: "ja-JP", label: "日本語" },
  { code: "ko-KR", label: "한국어" },
  { code: "hi-IN", label: "हिन्दी" },
  { code: "nl-NL", label: "Nederlands" },
  { code: "pl-PL", label: "Polski" },
  { code: "sv-SE", label: "Svenska" },
  { code: "id-ID", label: "Bahasa Indonesia" },
  { code: "vi-VN", label: "Tiếng Việt" },
  { code: "th-TH", label: "ไทย" },
  { code: "uk-UA", label: "Українська" },
  { code: "ro-RO", label: "Română" },
  { code: "el-GR", label: "Ελληνικά" },
  { code: "cs-CZ", label: "Čeština" },
  { code: "he-IL", label: "עברית" },
  { code: "da-DK", label: "Dansk" },
  { code: "fi-FI", label: "Suomi" },
  { code: "nb-NO", label: "Norsk" },
  { code: "fa-IR", label: "فارسی" },
] as const;

// Motor ses adı formatı: <locale>-<Name>Neural-<Gender> (app/services/voice.py)
export const VOICES = [
  { id: "en-US-AnaNeural-Female", label: "Ana (US, Female)", language: "en-US" },
  { id: "en-US-AndrewMultilingualNeural-Male", label: "Andrew Multilingual (US, Male)", language: "en-US" },
  { id: "en-US-AndrewNeural-Male", label: "Andrew (US, Male)", language: "en-US" },
  { id: "en-US-AriaNeural-Female", label: "Aria (US, Female)", language: "en-US" },
  { id: "en-US-AvaMultilingualNeural-Female", label: "Ava Multilingual (US, Female)", language: "en-US" },
  { id: "en-US-AvaNeural-Female", label: "Ava (US, Female)", language: "en-US" },
  { id: "en-US-BrianMultilingualNeural-Male", label: "Brian Multilingual (US, Male)", language: "en-US" },
  { id: "en-US-BrianNeural-Male", label: "Brian (US, Male)", language: "en-US" },
  { id: "en-US-ChristopherNeural-Male", label: "Christopher (US, Male)", language: "en-US" },
  { id: "en-US-EmmaMultilingualNeural-Female", label: "Emma Multilingual (US, Female)", language: "en-US" },
  { id: "en-US-EmmaNeural-Female", label: "Emma (US, Female)", language: "en-US" },
  { id: "en-US-EricNeural-Male", label: "Eric (US, Male)", language: "en-US" },
  { id: "en-US-GuyNeural-Male", label: "Guy (US, Male)", language: "en-US" },
  { id: "en-US-JennyNeural-Female", label: "Jenny (US, Female)", language: "en-US" },
  { id: "en-US-MichelleNeural-Female", label: "Michelle (US, Female)", language: "en-US" },
  { id: "en-US-RogerNeural-Male", label: "Roger (US, Male)", language: "en-US" },
  { id: "en-US-SteffanNeural-Male", label: "Steffan (US, Male)", language: "en-US" },
  { id: "en-GB-LibbyNeural-Female", label: "Libby (UK, Female)", language: "en-GB" },
  { id: "en-GB-MaisieNeural-Female", label: "Maisie (UK, Female)", language: "en-GB" },
  { id: "en-GB-RyanNeural-Male", label: "Ryan (UK, Male)", language: "en-GB" },
  { id: "en-GB-SoniaNeural-Female", label: "Sonia (UK, Female)", language: "en-GB" },
  { id: "en-GB-ThomasNeural-Male", label: "Thomas (UK, Male)", language: "en-GB" },
  { id: "tr-TR-AhmetNeural-Male", label: "Ahmet (TR, Male)", language: "tr-TR" },
  { id: "tr-TR-EmelNeural-Female", label: "Emel (TR, Female)", language: "tr-TR" },
  { id: "es-ES-AlvaroNeural-Male", label: "Alvaro (ES, Male)", language: "es-ES" },
  { id: "es-ES-ElviraNeural-Female", label: "Elvira (ES, Female)", language: "es-ES" },
  { id: "es-ES-XimenaNeural-Female", label: "Ximena (ES, Female)", language: "es-ES" },
  { id: "es-MX-DaliaNeural-Female", label: "Dalia (MX, Female)", language: "es-MX" },
  { id: "es-MX-JorgeNeural-Male", label: "Jorge (MX, Male)", language: "es-MX" },
  { id: "de-DE-AmalaNeural-Female", label: "Amala (DE, Female)", language: "de-DE" },
  { id: "de-DE-ConradNeural-Male", label: "Conrad (DE, Male)", language: "de-DE" },
  { id: "de-DE-FlorianMultilingualNeural-Male", label: "Florian Multilingual (DE, Male)", language: "de-DE" },
  { id: "de-DE-KatjaNeural-Female", label: "Katja (DE, Female)", language: "de-DE" },
  { id: "de-DE-KillianNeural-Male", label: "Killian (DE, Male)", language: "de-DE" },
  { id: "de-DE-SeraphinaMultilingualNeural-Female", label: "Seraphina Multilingual (DE, Female)", language: "de-DE" },
  { id: "fr-FR-DeniseNeural-Female", label: "Denise (FR, Female)", language: "fr-FR" },
  { id: "fr-FR-EloiseNeural-Female", label: "Eloise (FR, Female)", language: "fr-FR" },
  { id: "fr-FR-HenriNeural-Male", label: "Henri (FR, Male)", language: "fr-FR" },
  { id: "fr-FR-RemyMultilingualNeural-Male", label: "Remy Multilingual (FR, Male)", language: "fr-FR" },
  { id: "fr-FR-VivienneMultilingualNeural-Female", label: "Vivienne Multilingual (FR, Female)", language: "fr-FR" },
  { id: "pt-BR-AntonioNeural-Male", label: "Antonio (BR, Male)", language: "pt-BR" },
  { id: "pt-BR-FranciscaNeural-Female", label: "Francisca (BR, Female)", language: "pt-BR" },
  { id: "pt-BR-ThalitaMultilingualNeural-Female", label: "Thalita Multilingual (BR, Female)", language: "pt-BR" },
  { id: "it-IT-DiegoNeural-Male", label: "Diego (IT, Male)", language: "it-IT" },
  { id: "it-IT-ElsaNeural-Female", label: "Elsa (IT, Female)", language: "it-IT" },
  { id: "it-IT-GiuseppeMultilingualNeural-Male", label: "Giuseppe Multilingual (IT, Male)", language: "it-IT" },
  { id: "it-IT-IsabellaNeural-Female", label: "Isabella (IT, Female)", language: "it-IT" },
  { id: "ru-RU-DmitryNeural-Male", label: "Dmitry (RU, Male)", language: "ru-RU" },
  { id: "ru-RU-SvetlanaNeural-Female", label: "Svetlana (RU, Female)", language: "ru-RU" },
  { id: "ar-SA-HamedNeural-Male", label: "Hamed (SA, Male)", language: "ar-SA" },
  { id: "ar-SA-ZariyahNeural-Female", label: "Zariyah (SA, Female)", language: "ar-SA" },
  { id: "zh-CN-XiaoxiaoNeural-Female", label: "Xiaoxiao (CN, Female)", language: "zh-CN" },
  { id: "zh-CN-XiaoyiNeural-Female", label: "Xiaoyi (CN, Female)", language: "zh-CN" },
  { id: "zh-CN-YunjianNeural-Male", label: "Yunjian (CN, Male)", language: "zh-CN" },
  { id: "zh-CN-YunxiNeural-Male", label: "Yunxi (CN, Male)", language: "zh-CN" },
  { id: "zh-CN-YunxiaNeural-Male", label: "Yunxia (CN, Male)", language: "zh-CN" },
  { id: "zh-CN-YunyangNeural-Male", label: "Yunyang (CN, Male)", language: "zh-CN" },
  { id: "zh-CN-liaoning-XiaobeiNeural-Female", label: "Xiaobei (CN, Female)", language: "zh-CN" },
  { id: "zh-CN-shaanxi-XiaoniNeural-Female", label: "Xiaoni (CN, Female)", language: "zh-CN" },
  { id: "ja-JP-KeitaNeural-Male", label: "Keita (JP, Male)", language: "ja-JP" },
  { id: "ja-JP-NanamiNeural-Female", label: "Nanami (JP, Female)", language: "ja-JP" },
  { id: "ko-KR-HyunsuMultilingualNeural-Male", label: "Hyunsu Multilingual (KR, Male)", language: "ko-KR" },
  { id: "ko-KR-InJoonNeural-Male", label: "In Joon (KR, Male)", language: "ko-KR" },
  { id: "ko-KR-SunHiNeural-Female", label: "Sun Hi (KR, Female)", language: "ko-KR" },
  { id: "hi-IN-MadhurNeural-Male", label: "Madhur (IN, Male)", language: "hi-IN" },
  { id: "hi-IN-SwaraNeural-Female", label: "Swara (IN, Female)", language: "hi-IN" },
  { id: "nl-NL-ColetteNeural-Female", label: "Colette (NL, Female)", language: "nl-NL" },
  { id: "nl-NL-FennaNeural-Female", label: "Fenna (NL, Female)", language: "nl-NL" },
  { id: "nl-NL-MaartenNeural-Male", label: "Maarten (NL, Male)", language: "nl-NL" },
  { id: "pl-PL-MarekNeural-Male", label: "Marek (PL, Male)", language: "pl-PL" },
  { id: "pl-PL-ZofiaNeural-Female", label: "Zofia (PL, Female)", language: "pl-PL" },
  { id: "sv-SE-MattiasNeural-Male", label: "Mattias (SE, Male)", language: "sv-SE" },
  { id: "sv-SE-SofieNeural-Female", label: "Sofie (SE, Female)", language: "sv-SE" },
  { id: "id-ID-ArdiNeural-Male", label: "Ardi (ID, Male)", language: "id-ID" },
  { id: "id-ID-GadisNeural-Female", label: "Gadis (ID, Female)", language: "id-ID" },
  { id: "vi-VN-HoaiMyNeural-Female", label: "Hoai My (VN, Female)", language: "vi-VN" },
  { id: "vi-VN-NamMinhNeural-Male", label: "Nam Minh (VN, Male)", language: "vi-VN" },
  { id: "th-TH-NiwatNeural-Male", label: "Niwat (TH, Male)", language: "th-TH" },
  { id: "th-TH-PremwadeeNeural-Female", label: "Premwadee (TH, Female)", language: "th-TH" },
  { id: "uk-UA-OstapNeural-Male", label: "Ostap (UA, Male)", language: "uk-UA" },
  { id: "uk-UA-PolinaNeural-Female", label: "Polina (UA, Female)", language: "uk-UA" },
  { id: "ro-RO-AlinaNeural-Female", label: "Alina (RO, Female)", language: "ro-RO" },
  { id: "ro-RO-EmilNeural-Male", label: "Emil (RO, Male)", language: "ro-RO" },
  { id: "el-GR-AthinaNeural-Female", label: "Athina (GR, Female)", language: "el-GR" },
  { id: "el-GR-NestorasNeural-Male", label: "Nestoras (GR, Male)", language: "el-GR" },
  { id: "cs-CZ-AntoninNeural-Male", label: "Antonin (CZ, Male)", language: "cs-CZ" },
  { id: "cs-CZ-VlastaNeural-Female", label: "Vlasta (CZ, Female)", language: "cs-CZ" },
  { id: "he-IL-AvriNeural-Male", label: "Avri (IL, Male)", language: "he-IL" },
  { id: "he-IL-HilaNeural-Female", label: "Hila (IL, Female)", language: "he-IL" },
  { id: "da-DK-ChristelNeural-Female", label: "Christel (DK, Female)", language: "da-DK" },
  { id: "da-DK-JeppeNeural-Male", label: "Jeppe (DK, Male)", language: "da-DK" },
  { id: "fi-FI-HarriNeural-Male", label: "Harri (FI, Male)", language: "fi-FI" },
  { id: "fi-FI-NooraNeural-Female", label: "Noora (FI, Female)", language: "fi-FI" },
  { id: "nb-NO-FinnNeural-Male", label: "Finn (NO, Male)", language: "nb-NO" },
  { id: "nb-NO-PernilleNeural-Female", label: "Pernille (NO, Female)", language: "nb-NO" },
  { id: "fa-IR-DilaraNeural-Female", label: "Dilara (IR, Female)", language: "fa-IR" },
  { id: "fa-IR-FaridNeural-Male", label: "Farid (IR, Male)", language: "fa-IR" },
] as const;

export const ASPECTS = ["9:16", "16:9", "1:1"] as const;
export const DURATION_OPTIONS = [30, 60, 90, 180] as const;
export const MAX_SCRIPT_WORDS = 1200;

// Tek kanonik süre etiketi. Daha önce brief-step "30s/1m/90s/3m", özet
// paneli "1.5 min" basıyordu; aynı seçim için üç farklı yazım kullanıcıya
// farklı seçenekler varmış gibi görünüyordu.
export function formatDuration(seconds: number): string {
  if (seconds < 120) return `${seconds}s`;
  const minutes = seconds / 60;
  return `${Number.isInteger(minutes) ? minutes : minutes.toFixed(1)} min`;
}
