export const HERO_VIDEO_ID = "hero-demo-video";

export function HeroPhone() {
  return (
    <div className="flex justify-center">
      <div className="heroFloat relative">
        <div className="heroGlow absolute -inset-10 bg-[radial-gradient(circle_at_50%_40%,rgba(244,198,58,0.18),transparent_65%)] blur-[10px]" />
        <div className="relative h-[520px] w-[290px] rounded-[34px] border border-white/10 bg-elevated p-3 shadow-[0_40px_90px_rgba(0,0,0,0.55)]">
          <div className="relative h-full w-full overflow-hidden rounded-3xl bg-panel">
            {/* Gerçek Reelate çıktısı: 12 sn'lik sessiz döngü (366 KB) */}
            <video
              id={HERO_VIDEO_ID}
              className="absolute inset-0 h-full w-full object-cover"
              src="/hero-demo.mp4"
              poster="/hero-demo-poster.jpg"
              autoPlay
              muted
              loop
              playsInline
              preload="metadata"
              aria-label="A short video generated by Reelate, with AI voiceover captions burned in"
            />
            <div className="absolute left-3.5 top-3.5 inline-flex items-center gap-[7px] rounded-[7px] bg-black/35 px-[9px] py-[5px] font-mono-data text-[10px] tracking-[0.06em] text-bone/90">
              <span className="heroRec h-1.5 w-1.5 rounded-full bg-caption" />
              MADE WITH REELATE
            </div>
            <div className="absolute bottom-4 left-4 right-4 flex items-center gap-2">
              <div className="h-1 flex-1 overflow-hidden rounded-[3px] bg-white/25">
                <div className="h-full w-[62%] bg-caption" />
              </div>
              <span className="font-mono-data text-[10px] text-bone/90">
                0:38
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
