"use client";

import { useSyncExternalStore } from "react";
import {
  HERO_VIDEO_ID,
  getHeroMuted,
  getHeroMutedServer,
  setHeroMuted,
  subscribeHeroMuted,
} from "./hero-video-store";

export { HERO_VIDEO_ID };

export function HeroPhone() {
  const muted = useSyncExternalStore(
    subscribeHeroMuted,
    getHeroMuted,
    getHeroMutedServer,
  );

  function togglePlayback(video: HTMLVideoElement) {
    if (video.paused) void video.play().catch(() => {});
    else video.pause();
  }

  return (
    <div className="flex justify-center">
      <div className="heroFloat relative">
        <div className="heroGlow absolute -inset-10 bg-[radial-gradient(circle_at_50%_40%,rgba(244,198,58,0.18),transparent_65%)] blur-[10px]" />
        <div className="relative h-[520px] w-[290px] rounded-[34px] border border-white/10 bg-elevated p-3 shadow-[0_40px_90px_rgba(0,0,0,0.55)]">
          <div className="relative h-full w-full overflow-hidden rounded-3xl bg-panel">
            {/* Gerçek Reelate çıktısı: 12 sn'lik sesli döngü (~520 KB) */}
            <video
              id={HERO_VIDEO_ID}
              className="absolute inset-0 h-full w-full object-cover"
              src="/hero-demo.mp4"
              poster="/hero-demo-poster.jpg"
              autoPlay
              muted
              loop
              playsInline
              preload="metadata"
              onClick={(e) => togglePlayback(e.currentTarget)}
              aria-label="A 12-second video generated by Reelate, with AI voiceover and captions burned in"
            />
            <div className="absolute left-3.5 top-3.5 inline-flex items-center gap-[7px] rounded-[7px] bg-black/35 px-[9px] py-[5px] font-mono-data text-[10px] tracking-[0.06em] text-bone/90">
              <span className="heroRec h-1.5 w-1.5 rounded-full bg-caption" />
              MADE WITH REELATE
            </div>
            {/* Sağ üstte ve ikon-only: 290px'lik telefon karesinde metinli bir
                buton soldaki rozetle çakışıyordu; altyazı bandı da altta
                olduğu için buton üstte kalmalı. */}
            <button
              type="button"
              onClick={() => setHeroMuted(!muted)}
              aria-pressed={!muted}
              aria-label={muted ? "Play the demo with sound" : "Mute the demo"}
              title={muted ? "Tap for sound" : "Mute"}
              className="absolute right-3.5 top-3.5 flex h-8 w-8 items-center justify-center rounded-full bg-black/50 text-[13px] text-bone/90 backdrop-blur-sm transition-colors hover:bg-black/75 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-caption"
            >
              <span aria-hidden>{muted ? "🔇" : "🔊"}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
